#! /usr/bin/python

import argparse

parser = argparse.ArgumentParser(description='Search for words including partial word')

# Arguments

parser.add_argument('snippet', help='partial (or complete) string to search for in the words file')

args = parser.parse_args()

# Add a file you want the script to read
words = open('').readlines()
print([word for word in words if snippet in word.lower()])

print(matches)
