#! /usr/bin/python

import random
import os
import json

count = os.getenv("FILE_COUNT") or 100
# Add a file to enable the use of the script
words = [word.strip() for word in open('').readlines()]

for id in range(1, count + 1):
    amount = random.uniform(1.0, 1000.0) 
    content = {
            'topic': random.choice(words),
            'value': "%.2f" % amount
            }
    with open('./new/receipt-%s.json' % identifier, 'w') as f:
        json.dump(content, f)



